// <auto-generated />
using System;
using ATLAS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ATLAS.Data.Migrations
{
    [DbContext(typeof(AtlasContext))]
    [Migration("20260312170010_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ATLAS.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Assets");

                    b.HasDiscriminator().HasValue("Asset");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ATLAS.Models.AssetVulnerability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemediatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VulnerabilityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("VulnerabilityId");

                    b.ToTable("AssetVulnerabilities");
                });

            modelBuilder.Entity("ATLAS.Models.Vulnerability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AffectedSoftware")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CveId")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CvssScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemediationGuidance")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vulnerabilities");
                });

            modelBuilder.Entity("ATLAS.Models.CloudResource", b =>
                {
                    b.HasBaseType("ATLAS.Models.Asset");

                    b.Property<string>("AccountId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CloudProvider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("CloudResource");
                });

            modelBuilder.Entity("ATLAS.Models.Computer", b =>
                {
                    b.HasBaseType("ATLAS.Models.Asset");

                    b.Property<int>("ComputerType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CpuModel")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DomainJoined")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RamGb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Computer");
                });

            modelBuilder.Entity("ATLAS.Models.MobileDevice", b =>
                {
                    b.HasBaseType("ATLAS.Models.Asset");

                    b.Property<string>("Carrier")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Imei")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("MobileDeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.ToTable("Assets", t =>
                        {
                            t.Property("OperatingSystem")
                                .HasColumnName("MobileDevice_OperatingSystem");
                        });

                    b.HasDiscriminator().HasValue("MobileDevice");
                });

            modelBuilder.Entity("ATLAS.Models.NetworkDevice", b =>
                {
                    b.HasBaseType("ATLAS.Models.Asset");

                    b.Property<string>("Firmware")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Managed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NetworkDeviceType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PortCount")
                        .HasColumnType("INTEGER");

                    b.ToTable("Assets", t =>
                        {
                            t.Property("IpAddress")
                                .HasColumnName("NetworkDevice_IpAddress");
                        });

                    b.HasDiscriminator().HasValue("NetworkDevice");
                });

            modelBuilder.Entity("ATLAS.Models.Printer", b =>
                {
                    b.HasBaseType("ATLAS.Models.Asset");

                    b.Property<bool>("ColorCapable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NetworkConnected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrinterType")
                        .HasColumnType("INTEGER");

                    b.ToTable("Assets", t =>
                        {
                            t.Property("IpAddress")
                                .HasColumnName("Printer_IpAddress");
                        });

                    b.HasDiscriminator().HasValue("Printer");
                });

            modelBuilder.Entity("ATLAS.Models.SoftwareApplication", b =>
                {
                    b.HasBaseType("ATLAS.Models.Asset");

                    b.Property<int>("ApplicationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenseType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("SoftwareApplication");
                });

            modelBuilder.Entity("ATLAS.Models.AssetVulnerability", b =>
                {
                    b.HasOne("ATLAS.Models.Asset", "Asset")
                        .WithMany("AssetVulnerabilities")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ATLAS.Models.Vulnerability", "Vulnerability")
                        .WithMany("AssetVulnerabilities")
                        .HasForeignKey("VulnerabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Vulnerability");
                });

            modelBuilder.Entity("ATLAS.Models.Asset", b =>
                {
                    b.Navigation("AssetVulnerabilities");
                });

            modelBuilder.Entity("ATLAS.Models.Vulnerability", b =>
                {
                    b.Navigation("AssetVulnerabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
